Repository CSCI3100-B5/Classroom-Interchat, pull requests merged in 2021-04, with the labels that each got.

#30 Signup box code
  API.rest
  src/client/API.js
  src/client/auth/SignupBox.jsx
  src/server/auth/auth.controller.js
  src/server/auth/auth.validation.js
  src/server/config/express.js
  src/server/models/user.model.js
Labels: front-end

#29 React contexts for Axios, data store and Socket.io
  .eslintrc.json
  API.rest
  package.json
  public/index.html
  src/client/API.js
  src/client/App.jsx
  src/client/auth/Auth.jsx
  src/client/auth/LoginBox.jsx
  src/client/auth/SignupBox.jsx
  src/client/contexts/ApiProvider.jsx
  src/client/contexts/AxiosProvider.jsx
  src/client/contexts/DataStoreProvider.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/client/dataStore.js
  src/client/hooks/useLocalStorage.js
  src/server/auth/auth.controller.js
  src/server/auth/auth.validation.js
  src/server/classroom/external.listener.js
  src/server/config/server.js
  src/server/index.js
  src/server/index.listener.js
  src/server/index.route.js
  src/server/models/user.model.js
  yarn.lock
Labels: front-end

#31 API specs and database structures
  .gitattributes
  docs/API.rest
Labels: documentation

#32 Update /token API specs
  docs/API.rest
Labels: documentation

#34 Socket.io integration and history API fallback
  docs/API.rest
  public/index.html
  src/client/App.jsx
  src/client/auth/LoginBox.jsx
  src/client/classroom/index.jsx
  src/client/contexts/ApiProvider.jsx
  src/client/contexts/AxiosProvider.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/server/classroom/external.listener.js
  src/server/config/server.js
  src/server/helpers/middlewareWrap.js
  webpack.config.js
Labels: back-end, front-end

#36 Frontend file structure refresh
  .eslintrc.json
  docs/API.rest
  src/client/App.jsx
  src/client/account/Account.jsx
  src/client/account/ChangePassword.jsx
  src/client/account/EditAccountInfo.jsx
  src/client/account/LaunchApp.jsx
  src/client/account/ManageProfile.jsx
  src/client/account/ManageTokens.jsx
  src/client/account/TokensInfo.jsx
  src/client/auth/Auth.jsx
  src/client/auth/LoginBox.jsx
  src/client/auth/SignupBox.jsx
  src/client/classroom/CreateClassroom.jsx
  src/client/classroom/JoinClassroom.jsx
  src/client/classroom/index.jsx
  src/client/classroom/session/ClassroomSession.jsx
  src/client/classroom/session/chatbox/ChatBox.jsx
  src/client/classroom/session/chatbox/CreateQuiz.jsx
  src/client/classroom/session/chatbox/MessageCompose.jsx
  src/client/classroom/session/chatbox/MessageList.jsx
  src/client/classroom/session/chatbox/message/Message.jsx
  src/client/classroom/session/chatbox/message/QuestionMessage.jsx
  src/client/classroom/session/chatbox/message/QuizMessage.jsx
  src/client/classroom/session/chatbox/message/ReplyMessage.jsx
  src/client/classroom/session/chatbox/message/StatusMessage.jsx
  src/client/classroom/session/chatbox/message/TextMessage.jsx
  src/client/classroom/session/chatbox/message/quiz/MCQPrompt.jsx
  src/client/classroom/session/chatbox/message/quiz/MCQResult.jsx
  src/client/classroom/session/chatbox/message/quiz/QuizMessage.jsx
  src/client/classroom/session/chatbox/message/quiz/SAQPrompt.jsx
  src/client/classroom/session/chatbox/message/quiz/SAQResult.jsx
  src/client/classroom/session/dashboard/Dashboard.jsx
  src/client/classroom/session/dashboard/QuizCreate.jsx
  src/client/classroom/session/info/ClassroomInfo.jsx
  src/client/classroom/session/info/ClassroomPropType.js
  src/client/classroom/session/info/ParticipantList.jsx
  src/client/contexts/ApiProvider.jsx
  src/client/contexts/DataStoreProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/client/landing/Landing.jsx
  src/client/not-found/NotFound.jsx
  src/server/auth/auth.controller.js
Labels: front-end

#37 Helper code for data store
  src/client/auth/Auth.jsx
  src/client/auth/LoginBox.jsx
  src/client/classroom/CreateClassroom.jsx
  src/client/classroom/JoinClassroom.jsx
  src/client/classroom/session/ClassroomSession.jsx
  src/client/classroom/session/chatbox/MessageList.jsx
  src/client/classroom/session/chatbox/message/QuestionMessage.jsx
  src/client/classroom/session/chatbox/message/ReplyMessage.jsx
  src/client/classroom/session/chatbox/message/quiz/MCQResult.jsx
  src/client/classroom/session/chatbox/message/quiz/QuizMessage.jsx
  src/client/classroom/session/chatbox/message/quiz/SAQResult.jsx
  src/client/classroom/session/info/ClassroomInfo.jsx
  src/client/classroom/session/info/ParticipantList.jsx
  src/client/contexts/ApiProvider.jsx
  src/client/contexts/AxiosProvider.jsx
  src/client/contexts/DataStoreProvider.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/client/useStates.js
Labels: front-end

#44 Create classroom implementation
  API.rest
  docs/API.rest
  package.json
  src/client/classroom/CreateClassroom.jsx
  src/client/classroom/JoinClassroom.jsx
  src/client/classroom/session/chatbox/CreateQuiz.jsx
  src/client/classroom/session/chatbox/MessageCompose.jsx
  src/client/classroom/session/chatbox/message/Message.jsx
  src/client/classroom/session/chatbox/message/quiz/QuizMessage.jsx
  src/client/classroom/session/chatbox/message/quiz/SAQPrompt.jsx
  src/client/classroom/session/info/ParticipantList.jsx
  src/client/contexts/DataStoreProvider.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/server/auth/auth.controller.js
  src/server/classroom/external.controller.js
  src/server/classroom/external.events.js
  src/server/classroom/external.listener.js
  src/server/classroom/external.validation.js
  src/server/config/server.js
  src/server/helpers/socketValidatedEvents.js
  src/server/index.events.js
  src/server/index.js
  src/server/index.listener.js
  src/server/models/classroom.model.js
  src/server/models/message.model.js
  src/server/models/user.model.js
  src/server/user/user.controller.js
  yarn.lock
Labels: back-end, front-end

#46 Join classroom implementation
  .eslintrc.json
  docs/API.rest
  package.json
  src/client/classroom/CreateClassroom.jsx
  src/client/classroom/JoinClassroom.jsx
  src/client/classroom/session/ClassroomSession.jsx
  src/client/classroom/session/info/ClassroomInfo.jsx
  src/client/classroom/session/info/ParticipantList.jsx
  src/client/contexts/DataStoreProvider.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/client/hooks/useStates.js
  src/server/classroom/external.controller.js
  src/server/classroom/external.events.js
  src/server/classroom/external.validation.js
  src/server/config/server.js
  src/server/helpers/socketValidatedEvents.js
  src/server/index.events.js
  src/server/models/classroom.model.js
  src/server/models/user.model.js
  src/server/user/user.controller.js
  webpack.config.js
  yarn.lock
Labels: back-end, front-end

#50 Added markdown renderer with math and gfm plugins
  package.json
  src/client/classroom/session/chatbox/MessageCompose.jsx
  src/client/classroom/session/chatbox/message/MarkdownRender.jsx
  src/client/classroom/session/chatbox/message/QuestionMessage.jsx
  src/client/classroom/session/chatbox/message/ReplyMessage.jsx
  src/client/classroom/session/chatbox/message/TextMessage.jsx
  src/client/classroom/session/chatbox/message/quiz/MCQPrompt.jsx
  src/client/classroom/session/chatbox/message/quiz/SAQPrompt.jsx
  yarn.lock
Labels: front-end

#52 Implements instructor permission request and promote
  src/client/classroom/session/chatbox/MessageList.jsx
  src/client/classroom/session/info/ParticipantList.jsx
  src/client/contexts/DataStoreProvider.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/server/classroom/external/external.controller.js
  src/server/classroom/instructor/instructor.controller.js
  src/server/classroom/instructor/instructor.events.js
  src/server/classroom/instructor/instructor.validation.js
  src/server/index.events.js
Labels: back-end, front-end

#51 Quiz
  docs/API.rest
  docs/Glossary.md
  package.json
  src/client/account/Account.jsx
  src/client/auth/Auth.jsx
  src/client/classroom/JoinClassroom.jsx
  src/client/classroom/session/chatbox/CreateQuiz.jsx
  src/client/classroom/session/chatbox/MessageCompose.jsx
  src/client/classroom/session/chatbox/message/quiz/MCQPrompt.jsx
  src/client/classroom/session/chatbox/message/quiz/MCQResult.jsx
  src/client/classroom/session/chatbox/message/quiz/QuizMessage.jsx
  src/client/classroom/session/chatbox/message/quiz/SAQPrompt.jsx
  src/client/classroom/session/chatbox/message/quiz/SAQResult.jsx
  src/client/classroom/session/info/ParticipantList.jsx
  src/client/contexts/AxiosProvider.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/server/classroom/external/external.controller.js
  src/server/classroom/quiz/quiz.controller.js
  src/server/classroom/quiz/quiz.events.js
  src/server/classroom/quiz/quiz.validation.js
  src/server/index.events.js
  src/server/models/message.model.js
  src/server/models/quizanswer.model.js
  yarn.lock
Labels: back-end, front-end

#58 Added global toast
  package.json
  src/client/App.jsx
  src/client/ToastCenter.jsx
  src/client/ToastCenter.scoped.css
  src/client/account/ChangePassword.jsx
  src/client/account/ManageProfile.jsx
  src/client/auth/Auth.jsx
  src/client/auth/LoginBox.jsx
  src/client/auth/SignupBox.jsx
  src/client/classroom/CreateClassroom.jsx
  src/client/classroom/JoinClassroom.jsx
  src/client/classroom/index.jsx
  src/client/classroom/session/chatbox/CreateQuiz.jsx
  src/client/classroom/session/chatbox/MessageCompose.jsx
  src/client/classroom/session/chatbox/message/quiz/MCQPrompt.jsx
  src/client/classroom/session/chatbox/message/quiz/QuizMessage.jsx
  src/client/classroom/session/chatbox/message/quiz/SAQPrompt.jsx
  src/client/classroom/session/info/ClassroomInfo.jsx
  src/client/classroom/session/info/ParticipantList.jsx
  src/client/contexts/AxiosProvider.jsx
  src/client/contexts/DataStoreProvider.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/client/contexts/ToastProvider.jsx
  yarn.lock
Labels: front-end

#62 Classroom session styling
  package.json
  src/client/auth/Auth.jsx
  src/client/classroom/session/ClassroomSession.jsx
  src/client/classroom/session/ClassroomSession.scoped.css
  src/client/classroom/session/chatbox/ChatBox.jsx
  src/client/classroom/session/chatbox/ChatBox.scoped.css
  src/client/classroom/session/chatbox/MessageCompose.jsx
  src/client/classroom/session/chatbox/MessageCompose.scoped.css
  src/client/classroom/session/chatbox/MessageList.jsx
  src/client/classroom/session/chatbox/MessageList.scoped.css
  src/client/classroom/session/chatbox/message/QuestionMessage.jsx
  src/client/classroom/session/info/ClassroomInfo.jsx
  src/client/classroom/session/info/ClassroomInfo.scoped.css
  src/client/contexts/RealtimeProvider.jsx
  src/client/index.jsx
  src/client/main.css
  yarn.lock
Labels: front-end

#60 Token object
  public/index.html
  src/client/ToastCenter.scoped.css
  src/client/account/ManageTokens.jsx
  src/client/classroom/session/TokenAwarder.jsx
  src/client/classroom/session/chatbox/message/quiz/MCQResult.jsx
  src/client/classroom/session/chatbox/message/quiz/SAQResult.jsx
  src/client/classroom/session/info/ParticipantList.jsx
  src/client/contexts/ApiProvider.jsx
  src/client/contexts/AxiosProvider.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/client/landing/Icon@4x.png
  src/client/landing/Landing.jsx
  src/client/main.css
  src/server/classroom/instructor/instructor.controller.js
  src/server/classroom/instructor/instructor.events.js
  src/server/classroom/instructor/instructor.validation.js
  src/server/helpers/socketValidatedEvents.js
  src/server/index.route.js
  src/server/models/message.model.js
  src/server/models/token.model.js
  src/server/models/user.model.js
  src/server/token/token.controller.js
  src/server/token/token.route.js
  src/server/token/token.validation.js
  src/server/user/user.controller.js
  src/server/user/user.validation.js
  webpack.config.js
Labels: back-end, front-end

#61 Auth and account page css
  src/client/ToastCenter.jsx
  src/client/ToastCenter.scoped.css
  src/client/account/Account.jsx
  src/client/account/ChangePassword.jsx
  src/client/account/LaunchApp.jsx
  src/client/account/ManageProfile.jsx
  src/client/account/ManageTokens.jsx
  src/client/account/account.css
  src/client/auth/Auth.jsx
  src/client/auth/LoginBox.jsx
  src/client/auth/SignupBox.jsx
  src/client/auth/auth.css
  src/client/contexts/ApiProvider.jsx
  src/server/account/account.controller.js
  src/server/account/account.route.js
  src/server/account/auth.validation.js
  src/server/auth/auth.controller.js
  src/server/models/classroom.model.js
  src/server/models/message.model.js
  src/server/models/quizanswer.model.js
  src/server/models/token.model.js
  src/server/models/user.model.js
Labels: front-end

#63 Account implementation
  src/client/ToastCenter.jsx
  src/client/ToastCenter.scoped.css
  src/client/account/Account.jsx
  src/client/account/ChangePassword.jsx
  src/client/account/ManageProfile.jsx
  src/client/account/ManageTokens.jsx
  src/client/account/ManageTokens.scoped.css
  src/client/account/account.css
  src/client/auth/Auth.jsx
  src/client/contexts/ApiProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/client/landing/Landing.jsx
  src/server/config/server.js
  src/server/helpers/requireAuth.js
  src/server/models/user.model.js
  src/server/user/user.controller.js
  src/server/user/user.validation.js
Labels: back-end, front-end

#59 Kick demote logout
  src/client/account/Logout.jsx
  src/client/classroom/session/chatbox/MessageCompose.jsx
  src/client/classroom/session/chatbox/MessageCompose.scoped.css
  src/client/classroom/session/info/ParticipantList.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/server/classroom/external/external.controller.js
  src/server/classroom/external/external.events.js
  src/server/classroom/external/external.validation.js
  src/server/classroom/instructor/instructor.controller.js
  src/server/classroom/instructor/instructor.events.js
  src/server/classroom/instructor/instructor.validation.js
  src/server/classroom/message/message.controller.js
  src/server/classroom/quiz/quiz.controller.js
  src/server/models/classroom.model.js
Labels: back-end, front-end

#69 Participant list styling
  src/client/ToastCenter.jsx
  src/client/ToastCenter.scoped.css
  src/client/account/Account.jsx
  src/client/account/ChangePassword.jsx
  src/client/account/LaunchApp.jsx
  src/client/account/ManageProfile.jsx
  src/client/classroom/session/ClassroomSession.jsx
  src/client/classroom/session/TokenAwarder.jsx
  src/client/classroom/session/info/ClassroomInfo.jsx
  src/client/classroom/session/info/ClassroomInfo.scoped.css
  src/client/classroom/session/info/ParticipantList.jsx
  src/client/classroom/session/info/ParticipantList.scoped.css
  src/client/contexts/RealtimeProvider.jsx
  src/client/contexts/SocketProvider.jsx
  src/client/contexts/ToastProvider.jsx
Labels: front-end

#70 Verification email implementation
  package.json
  src/client/account/Account.jsx
  src/client/account/ChangePassword.jsx
  src/client/account/ManageProfile.jsx
  src/client/account/ManageProfile.scoped.css
  src/client/auth/SignupBox.jsx
  src/client/contexts/ApiProvider.jsx
  src/server/auth/auth.controller.js
  src/server/auth/auth.route.js
  src/server/auth/auth.validation.js
  src/server/config/config.js
  src/server/models/user.model.js
  src/server/user/user.controller.js
  yarn.lock
Labels: back-end, front-end

#71 Landing, auth and account page styling
  src/client/account/Account.jsx
  src/client/account/ManageTokens.jsx
  src/client/account/account.css
  src/client/auth/Auth.jsx
  src/client/auth/auth.css
  src/client/classroom/CreateClassroom.jsx
  src/client/classroom/JoinClassroom.jsx
  src/client/landing/Landing.jsx
  src/client/landing/Landing.scoped.css
Labels: front-end

#72 Peek classroom styling
  src/client/classroom/JoinClassroom.jsx
  src/client/classroom/JoinClassroom.scoped.css
  src/client/classroom/session/chatbox/ChatBox.jsx
  src/client/classroom/session/chatbox/MessageList.jsx
  src/client/classroom/session/chatbox/message/quiz/QuizMessage.jsx
  src/client/classroom/session/info/ClassroomInfo.jsx
  src/client/contexts/RealtimeProvider.jsx
  src/server/classroom/external/external.controller.js
  src/server/classroom/instructor/instructor.controller.js
  src/server/classroom/message/message.controller.js
  src/server/classroom/quiz/quiz.controller.js
Labels: front-end
